services:
  - type: web
    name: employee-reimbursement-portal
    runtime: ruby
    plan: free
    buildCommand: "bundle install && RAILS_ENV=production bundle exec rails assets:precompile && RAILS_ENV=production bundle exec rails db:migrate"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: RAILS_ENV
        value: production
      - key: RAILS_MASTER_KEY
        sync: false
    database:
      name: employee_reimbursement_portal_db
      plan: free
      databaseName: employee_reimbursement_portal_production
      user: employee_reimbursement_portal_user

